name: Python applicationj

on:
  issues:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install -r requirements.txt
      
      - name: Run main
        env:
          PAYLOAD: ${{ github.event.issue.body }}
        run: python main.py --file "$PAYLOAD"
